### ISSUE TITLE
Lab preps

### ISSUE THREAD

**Issue by kirill-korniakov** [Itseez-NNSU-SummerSchool2015/practice3-detection#1]
- [x] Подготовить картинки с объектами (логотипы OpenCV, Itseez, UNN, карты, и т.д.)
- [x] Подготовить тестовое видео для пары объектов
- [x] Написать тренировочные скрипты на Python (потому что Windows), чтобы было проще с ними работать
- [x] Реализовать простой тренировочный сэмпл (возможно стоит запускательный скрипт добавить, но скорее всего не нужно)
- [x] Залить в репозиторий негативы, которых хватает для большинства случаев. Они есть в директории Саши, а еще они есть у меня. Ну и в ITLab-Vision у нас были. Единственное, не очень хочется сильно увеличивать размер репозитория, я бы ориентировался максимум на 200-300 мб, а лучше ограничиться 100 мб.
- [x] Написать README
  - Пишем там план минимум (просто чтобы работало)
  - Потом предлагаем покрутить параметры, попробовать улучшить качество

Вот лог команд, которые использовал я (у Саши чуть другие в презентации)

```
$ ../opencv_createsamples -img ./src/itseez-logo-50.png -vec ./01.vec -bgcolor 255 -w 60 -h 25 -maxxangle .7 -maxyangle .7 -maxzangle 0.1
$ ./opencv_traincascade -numStages 5 -data ./cascade -vec 01.vec -bg negativesPascal.txt -numPos 500 -numNeg 500 -featureType LBP -w 60 -h 25
$ ./c-example-facedetect --cascade=./logo-detection/cascade/cascade.xml 0
```

**Comment by kirill-korniakov** [comment]
Паша, что-то странное у меня получилось. Если я использую те параметры, которые указаны выше, то у меня тоже огромная куча ложных срабатываний. В чем причина -- не знаю.

Пришлось добавлять опцию `-maxFalseAlarmRate 0.1`, c ней я получаю результаты, близкие к тому, что видел раньше. В чем дело не могу понять, но думаю с опцией тоже вполне все разумно получается. Полная команда выглядит так:

``` bash
$ ./opencv_traincascade -numStages 5 -data ./cascade -vec 01.vec -bg Neg.txt -maxFalseAlarmRate 0.1 -numPos 500 -numNeg 500 -featureType LBP -w 60 -h 25
```

На всякий случай выложил свой vec-файл и негативы сюда: https://drive.google.com/open?id=0Bz-THz8A_79UfmZwVlNyYmZVbjY0NnpSbHlUMnIxQUVRQm14dnlSa0N4d0RHeU1KcHF6c1E.

**Comment by druzhkov-paul** [comment]
Да, спасибо, теперь все встало на свои места.
